// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytkknjsqpcxwbjaoiwax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0a2tuanNxcGN4d2JqYW9pd2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTI4MzUsImV4cCI6MjA3MDY2ODgzNX0.4pP_gkAQb3YFhdPp7XyTU03PoRIVFcVyfGvNSn7A-SA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});